site_name: 桔子爸爸
nav:
  - Home: 
    - Home: index.md
    - Linux: linux/index.md
    - Python: python/index.md
    - Java: java/index.md
    - 前端知识: frontEnd/index.md
  - Linux: linux/index.md
  - Python: python/index.md
  - Java: 
    - Java: java/index.md
    - Spring: 
      - Spring: java/spring/index.md
      - FAQ: java/spring/spring-faq.md
      - Spring Response 封装: java/spring/spring-respDTO.md
  - 前端知识:
    - FrondEnd: frontEnd/index.md
    - Augular:
      - Angular: frontEnd/angular/index.md
      - Http 范式: frontEnd/angular/http.md

theme: 
  name: 'material'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
plugins:
  - mermaid2
  - search
extra_javascript:
    - js/mermaid.min.js